branch-defaults:
  main:
    environment: flask-continuous-delivery-env
    group_suffix: null
environment-defaults:
  flask-continuous-delivery-env:
    branch: main
    repository: origin
global:
  application_name: flask-continuous-delivery
  branch: main
  default_ec2_keyname: aws-eb
  default_platform: Python 3.7
  default_region: us-east-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  repository: origin
  sc: git
  workspace_type: Application
